// portfolio.v.1/src/components/Footer.jsx
import React from "react";
import logo from "../assets/img/logo-niver-mtz-salmon.png";
import iconGitHub from "../assets/img/icon-github.svg";
import iconLinkedin from "../assets/img/linkedin-brands.svg";
import iconTwitter from "../assets/img/icon-twitter_squared.svg";

const Footer = () => {
  return (
    <footer class="footer">
      <div class="footer-content">
        <div class="footer-logo">
          <img src={logo} height="50px" alt="logo bonito" />
        </div>
        <div class="social">
          <a
            class="button-icon"
            target="_blank"
            rel="noreferrer"
            href="https://github.com/NiverMtz"
          >
            <img src={iconGitHub} alt="" />
          </a>
          <a
            class="button-icon"
            target="_blank"
            rel="noreferrer"
            href="https://www.linkedin.com/in/niver-mtz/"
          >
            <img src={iconLinkedin} width="24px" alt="" />
          </a>
          <a
            class="button-icon"
            target="_blank"
            rel="noreferrer"
            href="https://twitter.com/nivermtz"
          >
            <img src={iconTwitter} alt="" />
          </a>
        </div>
        <div class="footer-copyright">
          <p>Hecho con el &#10084; por Niver.</p>
          <p>Copyright 2021 - Todos los derechos reservados.</p>
        </div>
      </div>
    </footer>
  );
};

export default Footer;

// portfolio-2.x.0/src/app/shared/footer/footer.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss'],
})
export class FooterComponent {
  today: number = Date.now();
  links = [
    {
      icon: 'pi pi-linkedin',
      href: 'https://www.linkedin.com/in/niver-mtz/',
    },
    {
      icon: 'pi pi-github',
      href: 'https://github.com/NiverMtz',
    },
    {
      icon: 'pi pi-twitter',
      href: 'https://twitter.com/NiverMtz',
    },
    {
      icon: 'pi pi-facebook',
      href: 'https://www.facebook.com/NiverMtz',
    },
  ];
}

<footer class="footer">
    <div class="footer-content">
        <div class="footer-logo">
            <img src="../../../assets/img/logo-niver-mtz-lila.png" height="50px" alt="logo bonito">
        </div>
        <div class="social is-hero">
            <a *ngFor="let link of links" [href]="link.href" target="_blank">
                <p-button [icon]="link.icon" styleClass="p-button-rounded"></p-button>
            </a>
        </div>
        <div class="footer-copyright text-white">
            <p>Hecho con el 🤍 por Niver.</p>
            <p>Copyright {{ today | date:'YYYY' }} - Todos los derechos reservados.</p>
        </div>
    </div>
</footer>
